build: College ERP Model
kevit-aayush-popat/Final-Task pull request #1
Opened 2023-10-26 05:17 UTC by kevit-aayush-popat

College ERP Model

2023-10-26 05:22 UTC, kevit-misri-pandya approved these changes

2023-10-31 06:03 UTC, kevit-misri-pandya requested changes

2023-10-31 06:03 UTC, kevit-misri-pandya commented on src/components/attendance/attendance.types.d.ts
> +    status: any
Don't Use Any! Can delare an enum for PRESENT , ABSENT status

2023-11-01 06:32 UTC, kevit-aayush-popat commented
changes in attendance module are completed

2023-11-22 11:06 UTC, kevit-misri-pandya commented on lib/__tests__/attendance.test.js
@kevit-aayush-popat Add a Lib in .gitignore

2023-11-22 11:20 UTC, kevit-misri-pandya requested changes

2023-11-22 11:20 UTC, kevit-misri-pandya commented on src/app.ts
> +// import * as http from 'http'
@kevit-aayush-popat Remove the commented code.

2023-11-22 11:20 UTC, kevit-misri-pandya commented on src/components/attendance/attendance.controller.ts
> +        // console.log(new Date('Wed Oct 19 2023'))
Remove console

2023-11-22 11:20 UTC, kevit-misri-pandya commented on src/components/attendance/attendance.error.ts
> +}
@kevit-aayush-popat Make Sure Alphabetical Order is Correct in Error Messages check in all Files

2023-11-22 11:20 UTC, kevit-misri-pandya commented on src/components/students/students.DAL.ts
> +    status?: any
@kevit-aayush-popat Don't use any

2023-11-22 11:20 UTC, kevit-misri-pandya commented on src/components/students/students.controller.ts
> +/// //left
??

2023-11-23 07:09 UTC, kevit-aayush-popat commented
refactored the changes assigned

2023-11-24 07:22 UTC, kevit-misri-pandya approved these changes

2023-11-24 07:32 UTC, merged